courseID: ITCS 3211/3212 and 1610/3210
courseTitle: STARS Service Learning Course
year: Spring 2016

description: Course Page for CS 5220
author: Stephen MacNeil
authorURL: http://stevemacn.github.io
email: smacnei2@uncc.edu
baseurl: "/service-learning-course/"
url: "http://stevemacn.github.io/service-learning-course/"

office-hours: "By appointment"
office-location: "Woodward 300"
schedule-link: https://stevemacn.youcanbook.me/

lecture-time: "Fri 2-4:45pm"
lecture-location: "CHHS 122"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
